//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelryStore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public int status { get; set; }
        public System.DateTime orderDate { get; set; }
        public System.DateTime deliveryDate { get; set; }
        public int pickupPoint { get; set; }
        public Nullable<int> client { get; set; }
        public int codeToReceive { get; set; }
    
        public virtual User User { get; set; }
        public virtual PickupPoint PickupPoint1 { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
    }
}
