//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelryStore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string articleNumber { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int category { get; set; }
        public byte[] photo { get; set; }
        public int manufacturer { get; set; }
        public int provider { get; set; }
        public decimal cost { get; set; }
        public Nullable<byte> discountAmount { get; set; }
        public Nullable<byte> maxDiscountAmount { get; set; }
        public int quantityInStock { get; set; }
        public int unit { get; set; }
    
        public virtual Manufacturer Manufacturer1 { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Provider Provider1 { get; set; }
        public virtual Unit Unit1 { get; set; }
    }
}
